### importing libraries:

In [1]:
import numpy as np
import tenseal as ts
import torch
from time import time
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

### Loading the dataset:

In [2]:
iris=load_iris()
data=pd.DataFrame(data=iris.data,columns=iris.feature_names)
data['target']=iris.target
data.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0

In [3]:
data=data[data['target']!=2]
# data=data[data['target']!=2]

### Cleaning the dataset:

In [4]:
data.shape

(100, 5)

##### removing rows with missing values:

In [5]:
data=data.dropna()
data.shape

(100, 5)

##### balancing the data:

In [6]:
grouped=data.groupby('target')
grouped.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
50       1  
51       1  
52       1  
53       1  
54       1

In [7]:
data=grouped.apply(lambda x: x.sample(grouped.size().min(),random_state=73).reset_index(drop=True))
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target                                                             
0      0                5.2               3.4                1.4   
       1                5.4               3.4                1.7   
       2                5.0               3.3                1.4   
       3                4.9               3.1                1.5   
       4                5.2               4.1                1.5   

          petal width (cm)  target  
target                              
0      0               0.2       0  
       1               0.2       0  
       2               0.2       0  
       3               0.2       0  
       4               0.1       0

In [8]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target                                                              
0      0                 5.2               3.4                1.4   
       1                 5.4               3.4                1.7   
       2                 5.0               3.3                1.4   
       3                 4.9               3.1                1.5   
       4                 5.2               4.1                1.5   
...                      ...               ...                ...   
1      45                5.6               3.0                4.5   
       46                5.0               2.0                3.5   
       47                5.7               2.9                4.2   
       48                6.2               2.2                4.5   
       49                6.3               2.5                4.9   

           petal width (cm)  target  
target                               
0      0                0.2       0  
       1                0.2       0  
       2                0.2       0  
       3                0.2       0  
       4                0.1       0  
...                     ...     ...  
1      45               1.5       1  
       46               1.0       1  
       47               1.3       1  
       48               1.5       1  
       49               1.5       1  

[100 rows x 5 columns]

In [9]:
data.shape

(100, 5)

In [10]:
y=torch.tensor(data["target"].values).float()
y

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
y=y.unsqueeze(1)

In [12]:
y

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [13]:
data=data.drop("target",axis=1)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target                                                             
0      0                5.2               3.4                1.4   
       1                5.4               3.4                1.7   
       2                5.0               3.3                1.4   
       3                4.9               3.1                1.5   
       4                5.2               4.1                1.5   

          petal width (cm)  
target                      
0      0               0.2  
       1               0.2  
       2               0.2  
       3               0.2  
       4               0.1

##### normalizing data:

In [14]:
data=(data-data.mean())/data.std()
x=torch.tensor(data.values).float()
x

tensor([[-4.2232e-01,  6.2874e-01, -1.0079e+00, -1.0369e+00],
        [-1.1064e-01,  6.2874e-01, -8.0094e-01, -1.0369e+00],
        [-7.3399e-01,  4.1985e-01, -1.0079e+00, -1.0369e+00],
        [-8.8983e-01,  2.0888e-03, -9.3891e-01, -1.0369e+00],
        [-4.2232e-01,  2.0909e+00, -9.3891e-01, -1.2138e+00],
        [-1.2015e+00,  2.1097e-01, -1.0769e+00, -1.0369e+00],
        [-7.3399e-01,  2.1097e-01, -1.1459e+00, -1.0369e+00],
        [-1.0457e+00,  6.2874e-01, -6.6297e-01, -1.0369e+00],
        [-5.7815e-01,  8.3762e-01, -1.0079e+00, -1.0369e+00],
        [-2.6648e-01,  1.2554e+00, -9.3891e-01, -1.0369e+00],
        [-1.0457e+00, -2.0679e-01, -1.0079e+00, -8.5994e-01],
        [-5.7815e-01,  4.1985e-01, -8.0094e-01, -5.0606e-01],
        [-1.8248e+00, -2.0679e-01, -1.2149e+00, -1.2138e+00],
        [-1.3573e+00,  6.2874e-01, -1.0079e+00, -8.5994e-01],
        [-1.1064e-01,  1.6731e+00, -8.0094e-01, -6.8300e-01],
        [-8.8983e-01,  1.0465e+00, -1.0079e+00, -1.2138e+00],
        

In [15]:
x.shape

torch.Size([100, 4])

In [16]:
y.shape

torch.Size([100, 1])

##### dividing the dataset into training and testing:

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,stratify=y,test_size=0.3)

In [18]:
len(x_train),len(x_test),len(y_train),len(y_test)

(70, 30, 70, 30)

### Creating a neural network that facilitates Logisitic Regression Classification:

##### A class that creates a neural network for Logistic Regression:

In [19]:
class LR(torch.nn.Module):
    def __init__(self,n_features,num_classes):
        super(LR,self).__init__()
        self.lr=torch.nn.Linear(n_features,num_classes)
        
    def forward(self,x):
        out=torch.sigmoid(self.lr(x))
        return out

##### creating a neural network using LR class:

In [20]:
num_classes=1
n_features=x_train.shape[1]
model=LR(n_features,num_classes)

##### using gradient descent with a learning_rate=1

In [21]:
optim=torch.optim.SGD(model.parameters(),lr=1)

##### using Binary Cross Entropy Loss

In [22]:
criterion=torch.nn.CrossEntropyLoss()

### Training the neural network on training data:

In [23]:
EPOCHS=5
def train(model,optim,criterion,x,y,epochs=EPOCHS):
    for e in range(1,epochs+1):
        optim.zero_grad()
        out=model(x)
        loss=criterion(out,y)
        loss.backward()
        optim.step()
        print(f"Loss at epoch {e}={loss.data}")
    return model

t1=time()
model=train(model,optim,criterion,x_train,y_train)
t2=time()
print(f'time taken to train the LR model on unencrypted data={t2-t1}ms')

Loss at epoch 1=-0.0
Loss at epoch 2=-0.0
Loss at epoch 3=-0.0
Loss at epoch 4=-0.0
Loss at epoch 5=-0.0
time taken to train the LR model on unencrypted data=0.004999399185180664ms


In [24]:
def accuracy(model,x,y):
    out=model(x)
    correct=torch.abs(y-out)<0.5
    return correct.float().mean()

plain_accuracy=accuracy(model,x_test,y_test)
print(f"Accuracy on plain test_set:{plain_accuracy}")

Accuracy on plain test_set:0.0
