### importing libraries:

In [1]:
import numpy as np
import tenseal as ts
import torch
from time import time
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

### Loading the dataset:

In [2]:
iris=load_iris()
data=pd.DataFrame(data=iris.data,columns=iris.feature_names)
data['target']=iris.target
data.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0

In [3]:
data=data[data['target']!=2]

In [4]:
data.shape

(100, 5)

### Cleaning the dataset:

##### balancing the data:

In [5]:
grouped=data.groupby('target')
grouped.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
50       1  
51       1  
52       1  
53       1  
54       1

In [6]:
data=grouped.apply(lambda x: x.sample(grouped.size().min(),random_state=73).reset_index(drop=True))
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target                                                             
0      0                5.2               3.4                1.4   
       1                5.4               3.4                1.7   
       2                5.0               3.3                1.4   
       3                4.9               3.1                1.5   
       4                5.2               4.1                1.5   

          petal width (cm)  target  
target                              
0      0               0.2       0  
       1               0.2       0  
       2               0.2       0  
       3               0.2       0  
       4               0.1       0

In [7]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target                                                              
0      0                 5.2               3.4                1.4   
       1                 5.4               3.4                1.7   
       2                 5.0               3.3                1.4   
       3                 4.9               3.1                1.5   
       4                 5.2               4.1                1.5   
...                      ...               ...                ...   
1      45                5.6               3.0                4.5   
       46                5.0               2.0                3.5   
       47                5.7               2.9                4.2   
       48                6.2               2.2                4.5   
       49                6.3               2.5                4.9   

           petal width (cm)  target  
target                               
0      0                0.2       0  
       1                0.2       0  
       2                0.2       0  
       3                0.2       0  
       4                0.1       0  
...                     ...     ...  
1      45               1.5       1  
       46               1.0       1  
       47               1.3       1  
       48               1.5       1  
       49               1.5       1  

[100 rows x 5 columns]

In [8]:
y=torch.tensor(data["target"].values).float()
y

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
y=y.unsqueeze(1)
y

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [10]:
data=data.drop("target",axis=1)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
target                                                             
0      0                5.2               3.4                1.4   
       1                5.4               3.4                1.7   
       2                5.0               3.3                1.4   
       3                4.9               3.1                1.5   
       4                5.2               4.1                1.5   

          petal width (cm)  
target                      
0      0               0.2  
       1               0.2  
       2               0.2  
       3               0.2  
       4               0.1

##### normalizing data:

In [11]:
data=(data-data.mean())/data.std()
x=torch.tensor(data.values).float()
x

tensor([[-4.2232e-01,  6.2874e-01, -1.0079e+00, -1.0369e+00],
        [-1.1064e-01,  6.2874e-01, -8.0094e-01, -1.0369e+00],
        [-7.3399e-01,  4.1985e-01, -1.0079e+00, -1.0369e+00],
        [-8.8983e-01,  2.0888e-03, -9.3891e-01, -1.0369e+00],
        [-4.2232e-01,  2.0909e+00, -9.3891e-01, -1.2138e+00],
        [-1.2015e+00,  2.1097e-01, -1.0769e+00, -1.0369e+00],
        [-7.3399e-01,  2.1097e-01, -1.1459e+00, -1.0369e+00],
        [-1.0457e+00,  6.2874e-01, -6.6297e-01, -1.0369e+00],
        [-5.7815e-01,  8.3762e-01, -1.0079e+00, -1.0369e+00],
        [-2.6648e-01,  1.2554e+00, -9.3891e-01, -1.0369e+00],
        [-1.0457e+00, -2.0679e-01, -1.0079e+00, -8.5994e-01],
        [-5.7815e-01,  4.1985e-01, -8.0094e-01, -5.0606e-01],
        [-1.8248e+00, -2.0679e-01, -1.2149e+00, -1.2138e+00],
        [-1.3573e+00,  6.2874e-01, -1.0079e+00, -8.5994e-01],
        [-1.1064e-01,  1.6731e+00, -8.0094e-01, -6.8300e-01],
        [-8.8983e-01,  1.0465e+00, -1.0079e+00, -1.2138e+00],
        

In [12]:
x.shape

torch.Size([100, 4])

In [13]:
y.shape

torch.Size([100, 1])

##### dividing the dataset into training and testing:

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,stratify=y,test_size=0.3)

In [15]:
len(x_train),len(x_test),len(y_train),len(y_test)

(70, 30, 70, 30)

### Creating a neural network that facilitates Logisitic Regression Classification:

##### A class that creates a neural network for Logistic Regression:

In [16]:
class LR(torch.nn.Module):
    def __init__(self,n_features):
        super(LR,self).__init__()
        self.lr=torch.nn.Linear(n_features,1)
        
    def forward(self,x):
        out=torch.sigmoid(self.lr(x))
        return out

##### extracting number of features:

In [17]:
n_features=x_train.shape[1]

### _______________________________________________________________RISKY PART______________________________________________________________________

### Creating TenSEAL context for encrypting data:

In [18]:
poly_mod_degree=8192
coeff_mod_bit_sizes=[40,21,21,21,21,21,21,40]
ctx_training=ts.context(ts.SCHEME_TYPE.CKKS,poly_mod_degree,-1,coeff_mod_bit_sizes)
ctx_training.global_scale=2**21
ctx_training.generate_galois_keys()

In [19]:
print("Is the context private?",("Yes" if ctx_training.is_private() else "No"))

Is the context private? Yes


In [20]:
t_start=time()
enc_x_test=[ts.ckks_vector(ctx_training,x.tolist()) for x in x_test]
enc_y_test=[ts.ckks_vector(ctx_training,y.tolist()) for y in y_test]
enc_x_train=[ts.ckks_vector(ctx_training,x.tolist()) for x in x_train]
enc_y_train=[ts.ckks_vector(ctx_training,y.tolist()) for y in y_train]
t_end=time()

print(f'data trained in {t_end-t_start}s')

data trained in 2.058173656463623s


### Training Logistic Regression model on encrypted data:

##### Creating a class that creates a neural network for Logistic Regression on encrypted data:

In [21]:
class EncryptedLR:
    
    def __init__(self,torch_lr):
        self.weight=torch_lr.lr.weight.data.tolist()[0]
        self.bias=torch_lr.lr.bias.data.tolist()
        self._delta_w = 0
        self._delta_b = 0
        self._count = 0
        
    def forward(self,enc_x):
        enc_out=enc_x.dot(self.weight)+self.bias
        enc_out=EncryptedLR.sigmoid(enc_out)
        return enc_out
    
    def backward(self,enc_x,enc_out,enc_y):
        out_minus_y=(enc_out-enc_y)
        self._delta_w+=enc_x*out_minus_y
        self._delta_b+=out_minus_y
        self._count+=1
        
    def update_parameters(self):
        if self._count==0:
            raise RuntimeError("You should at least run one forward iteration")

        self.weight-=self._delta_w*(1/self._count)+self.weight*0.05
        self.bias-=self._delta_b*(1/self._count)
    
        self._delta_w=0
        self._delta_b=0
        self._count=0
    
    @staticmethod
    def sigmoid(enc_x):
        # using polynomial approximation of degree 3 which fits the function pretty well in the range [-5,5]. Source: https://eprint.iacr.org/2018/462.pdf
        return enc_x.polyval([0.5,0.197,0,-0.004])
    
    def plain_accuracy(self,x_test,y_test):
        # evaluate accuracy of the model on
        # the plain (x_test, y_test) dataset
        w=torch.tensor(self.weight)
        b=torch.tensor(self.bias)
        out=torch.sigmoid(x_test.matmul(w)+b).reshape(-1, 1)
        correct=torch.abs(y_test-out)<0.5
        return correct.float().mean()    
    
    def encrypt(self,context):
        self.weight=ts.ckks_vector(context,self.weight)
        self.bias=ts.ckks_vector(context,self.bias)
        
    def decrypt(self):
        self.weight=self.weight.decrypt()
        self.bias=self.bias.decrypt()
        
    def __call__(self,*args,**kwargs):
        return self.forward(*args,**kwargs)

##### training the model on encrypted data and testing it on plain data:

In [22]:
EPOCHS=3
eelr = EncryptedLR(LR(n_features))
accuracy = eelr.plain_accuracy(x_test, y_test)
print(f"Accuracy at epoch #0 is {accuracy}")

times = []
for epoch in range(EPOCHS):
    eelr.encrypt(ctx_training)
    
    # if you want to keep an eye on the distribution to make sure
    # the function approximation is still working fine
    # WARNING: this operation is time consuming
    # encrypted_out_distribution(eelr, enc_x_train)
    
    t_start = time()
    for enc_x, enc_y in zip(enc_x_train, enc_y_train):
        enc_out = eelr.forward(enc_x)
        eelr.backward(enc_x, enc_out, enc_y)
    eelr.update_parameters()
    t_end = time()
    times.append(t_end - t_start)
    
    eelr.decrypt()
    accuracy = eelr.plain_accuracy(x_test, y_test)
    print(f"Accuracy at epoch #{epoch + 1} is {accuracy}")


print(f"\nAverage time per epoch: {int(sum(times) / len(times))} seconds")
print(f"Final accuracy is {accuracy}")

Accuracy at epoch #0 is 0.30000001192092896
Accuracy at epoch #1 is 1.0
Accuracy at epoch #2 is 1.0
Accuracy at epoch #3 is 1.0

Average time per epoch: 5 seconds
Final accuracy is 1.0


##### testing the model on encrypted data:

In [23]:
def encrypted_evaluation(model, enc_x_test, y_test):
    t_start = time()
    
    correct = 0
    for enc_x, y in zip(enc_x_test, y_test):
        # encrypted evaluation
        enc_out = model(enc_x)
        # plain comparison
        out = enc_out.decrypt()
        out = torch.tensor(out)
        out = torch.sigmoid(out)
        if torch.abs(out - y) < 0.5:
            correct += 1
    
    t_end = time()
    print(f"Evaluated test_set of {len(x_test)} entries in {int(t_end - t_start)} seconds")
    print(f"Accuracy: {correct}/{len(x_test)} = {correct / len(x_test)}")
    return correct / len(x_test)
    

encrypted_accuracy = encrypted_evaluation(eelr, enc_x_test, y_test)

Evaluated test_set of 30 entries in 1 seconds
Accuracy: 0/30 = 0.0
